/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Sinh Nguyễn (https://sketchfab.com/nlsinh)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/hero-d51e535a713c4491b5dcb4b8632ff5cd
Title: Hero
*/
"use client";
import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function HeroModel(props) {
  const group = useRef();
  const modelRef = useRef();
  const { nodes, materials, animations } = useGLTF('/models/Hero-transformed.glb');
  const { actions } = useAnimations(animations, group);

  // Animation logic
  useFrame((state) => {
    if (modelRef.current) {
      modelRef.current.position.y = -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;
    }
  });

  return (

    <group ref={group} {...props} dispose={null}
        ref={modelRef}
        position={[0,0,0,0]}
        scale={[0.25,0.25,0.25]}
        rotation={[0.-0.25,0.1,0.1]}
        >

      <group name="Sketchfab_Scene">
        <group name="RootNode">
          <group name="power" position={[0, 0.039, 0]} scale={[0.943, 1, 0.943]}>
            <mesh
              name="power_blinn1_0"
              castShadow
              receiveShadow
              geometry={nodes.power_blinn1_0.geometry}
              material={materials.blinn1}
            />
          </group>
        </group>
        <primitive object={nodes._rootJoint} />
        <skinnedMesh
          name="Object_88"
          geometry={nodes.Object_88.geometry}
          material={materials.warriormodel1warrior}
          skeleton={nodes.Object_88.skeleton}
        />
        <group name="Character1_Ctrl_Reference">
          <group
            name="Character1_Ctrl_HipsEffector"
            position={[-0.662, 2.739, -0.116]}
            rotation={[0.262, 1.083, -0.119]}
          />
          <group
            name="Character1_Ctrl_LeftAnkleEffector"
            position={[-0.072, 0.51, -2.497]}
            rotation={[0, 1.501, 0]}
          />
          <group
            name="Character1_Ctrl_RightAnkleEffector"
            position={[-1.142, 0.54, 1.778]}
            rotation={[0, 0.033, 0]}
          />
          <group
            name="Character1_Ctrl_LeftWristEffector"
            position={[2.135, 6.092, -1.396]}
            rotation={[0.642, -0.48, 0.483]}
          />
          <group
            name="Character1_Ctrl_RightWristEffector"
            position={[-1.602, 4.692, 2.86]}
            rotation={[-0.879, 0.379, 1.308]}
          />
          <group
            name="Character1_Ctrl_LeftKneeEffector"
            position={[0.595, 1.831, -1.652]}
            rotation={[1.745, 1.134, -1.203]}
          />
          <group
            name="Character1_Ctrl_RightKneeEffector"
            position={[-1.004, 2.194, 2.148]}
            rotation={[0.239, 0.102, -0.078]}
          />
          <group
            name="Character1_Ctrl_LeftElbowEffector"
            position={[0.84, 6.918, -1.896]}
            rotation={[0.073, 0.111, 0.224]}
          />
          <group
            name="Character1_Ctrl_RightElbowEffector"
            position={[-2.14, 5.745, 1.728]}
            rotation={[-0.491, 1.09, 0.671]}
          />
          <group
            name="Character1_Ctrl_ChestOriginEffector"
            position={[-0.526, 5.171, 0.268]}
            rotation={[0.305, 1.066, -0.148]}
          />
          <group
            name="Character1_Ctrl_ChestEndEffector"
            position={[-0.217, 7.653, 0.849]}
            rotation={[0.616, 0.894, -0.344]}
          />
          <group
            name="Character1_Ctrl_LeftFootEffector"
            position={[0.903, 0.038, -2.428]}
            rotation={[0, 1.501, 0]}
          />
          <group
            name="Character1_Ctrl_RightFootEffector"
            position={[-1.11, 0.068, 2.755]}
            rotation={[0, 0.033, 0]}
          />
          <group
            name="Character1_Ctrl_LeftShoulderEffector"
            position={[0.326, 7.789, 0.125]}
            rotation={[0.989, 0.641, -0.698]}
          />
          <group
            name="Character1_Ctrl_RightShoulderEffector"
            position={[-0.76, 7.516, 1.586]}
            rotation={[0.396, 0.51, 0.202]}
          />
          <group
            name="Character1_Ctrl_HeadEffector"
            position={[-0.379, 11.938, 1.366]}
            rotation={[0.04, 0.163, 0.097]}
          />
          <group
            name="Character1_Ctrl_LeftHipEffector"
            position={[-0.181, 2.856, -1.024]}
            rotation={[-0.787, 0.981, 1.307]}
          />
          <group
            name="Character1_Ctrl_RightHipEffector"
            position={[-1.144, 2.623, 0.793]}
            rotation={[-1.29, 0.163, 0.171]}
          />
          <group
            name="Character1_Ctrl_LeftHandThumbEffector"
            position={[1.83, 5.549, -0.891]}
            rotation={[0.642, -0.48, 0.483]}
          />
          <group
            name="Character1_Ctrl_LeftHandMiddleEffector"
            position={[2.685, 4.775, -1.275]}
            rotation={[0.642, -0.48, 0.483]}
          />
          <group
            name="Character1_Ctrl_RightHandThumbEffector"
            position={[-0.854, 4.785, 2.598]}
            rotation={[3.117, 0.609, 2.68]}
          />
          <group
            name="Character1_Ctrl_RightHandMiddleEffector"
            position={[-0.797, 4.541, 2.844]}
            rotation={[-1.409, 0.312, -3.051]}
          />
          <group
            name="Character1_Ctrl_Hips"
            position={[-0.636, 3.206, -0.042]}
            rotation={[0.262, 1.083, -0.119]}>
            <group
              name="Character1_Ctrl_LeftUpLeg"
              position={[1.035, -0.473, 0]}
              rotation={[-0.52, 0.091, 0.519]}>
              <group
                name="Character1_Ctrl_LeftLeg"
                position={[0.107, -1.428, 0]}
                rotation={[0.966, -0.027, -0.044]}>
                <group
                  name="Character1_Ctrl_LeftFoot"
                  position={[0, -1.706, 0]}
                  rotation={[-0.441, 0.091, -0.5]}>
                  <group name="Character1_Ctrl_LeftToeBase" position={[0, -0.472, 0.977]} />
                </group>
              </group>
            </group>
            <group
              name="Character1_Ctrl_RightUpLeg"
              position={[-1.035, -0.473, 0]}
              rotation={[-1.408, -0.058, -0.889]}>
              <group
                name="Character1_Ctrl_RightLeg"
                position={[-0.107, -1.428, 0]}
                rotation={[1.495, -0.085, 0.071]}>
                <group
                  name="Character1_Ctrl_RightFoot"
                  position={[0, -1.706, 0]}
                  rotation={[-0.223, -0.086, 0.057]}>
                  <group name="Character1_Ctrl_RightToeBase" position={[0, -0.472, 0.977]} />
                </group>
              </group>
            </group>
            <group
              name="Character1_Ctrl_Spine"
              position={[0, 1.993, 0]}
              rotation={[0.023, -0.014, 0.009]}>
              <group
                name="Character1_Ctrl_Spine1"
                position={[0, 1.693, 0]}
                rotation={[0.214, -0.116, 0.076]}>
                <group
                  name="Character1_Ctrl_LeftArm"
                  position={[0.92, 0.89, 0]}
                  rotation={[0.354, -0.097, -0.082]}>
                  <group
                    name="Character1_Ctrl_LeftForeArm"
                    position={[1.898, -1.235, 0]}
                    rotation={[-0.64, -0.801, 0.265]}>
                    <group
                      name="Character1_Ctrl_LeftHand"
                      position={[1.058, -1.025, 0.719]}
                      rotation={[0.464, -0.687, 0.315]}>
                      <group name="Character1_Ctrl_LeftHandThumb1" position={[0.121, -0.25, 0.232]}>
                        <group
                          name="Character1_Ctrl_LeftHandThumb2"
                          position={[-0.066, 0.019, 0.127]}>
                          <group
                            name="Character1_Ctrl_LeftHandThumb3"
                            position={[-0.045, 0.057, 0.254]}>
                            <group
                              name="Character1_Ctrl_LeftHandThumb4"
                              position={[-0.013, 0.016, 0.176]}
                            />
                          </group>
                        </group>
                      </group>
                      <group
                        name="Character1_Ctrl_LeftHandMiddle1"
                        position={[0.446, -0.501, 0.315]}>
                        <group
                          name="Character1_Ctrl_LeftHandMiddle2"
                          position={[0.097, -0.316, 0.097]}>
                          <group
                            name="Character1_Ctrl_LeftHandMiddle3"
                            position={[-0.114, -0.333, 0.063]}>
                            <group
                              name="Character1_Ctrl_LeftHandMiddle4"
                              position={[-0.057, -0.154, 0.046]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Character1_Ctrl_RightArm"
                  position={[-0.92, 0.89, 0]}
                  rotation={[-0.079, -0.406, 0.378]}>
                  <group
                    name="Character1_Ctrl_RightForeArm"
                    position={[-1.898, -1.235, 0]}
                    rotation={[-0.296, 0.747, -0.096]}>
                    <group
                      name="Character1_Ctrl_RightHand"
                      position={[-1.058, -1.025, 0.719]}
                      rotation={[-0.723, -0.244, 0.263]}>
                      <group
                        name="Character1_Ctrl_RightHandThumb1"
                        position={[-0.121, -0.25, 0.232]}
                        rotation={[0.991, 0.456, -0.746]}>
                        <group
                          name="Character1_Ctrl_RightHandThumb2"
                          position={[0.066, 0.019, 0.127]}
                          rotation={[-0.003, 0.208, -0.045]}>
                          <group
                            name="Character1_Ctrl_RightHandThumb3"
                            position={[0.045, 0.057, 0.254]}
                            rotation={[0.025, 0.732, -0.079]}>
                            <group
                              name="Character1_Ctrl_RightHandThumb4"
                              position={[0.013, 0.016, 0.176]}
                            />
                          </group>
                        </group>
                      </group>
                      <group
                        name="Character1_Ctrl_RightHandMiddle1"
                        position={[-0.446, -0.501, 0.315]}
                        rotation={[0.118, 0.47, 0.481]}>
                        <group
                          name="Character1_Ctrl_RightHandMiddle2"
                          position={[-0.097, -0.316, 0.097]}
                          rotation={[-0.061, 0.084, 0.592]}>
                          <group
                            name="Character1_Ctrl_RightHandMiddle3"
                            position={[0.114, -0.333, 0.063]}
                            rotation={[-0.095, 0.126, 0.583]}>
                            <group
                              name="Character1_Ctrl_RightHandMiddle4"
                              position={[0.057, -0.154, 0.046]}
                            />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
                <group
                  name="Character1_Ctrl_Neck"
                  position={[0, 1.693, 0]}
                  rotation={[-0.445, -0.764, -0.052]}>
                  <group name="Character1_Ctrl_Head" position={[0, 3.588, 0]} />
                </group>
              </group>
            </group>
          </group>
        </group>
        <mesh
          name="pPlane3_blinn3_0"
          castShadow
          receiveShadow
          geometry={nodes.pPlane3_blinn3_0.geometry}
          material={materials.blinn3}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Hero-transformed.glb')